# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2602b58e340250ef2bb439b22e341cbb6d046d6c79cb602858a35633b9f11eaa69bbb771e4f3257dfb671b08855a0768bec515e188aa51c6a529a4c597ab4b7f

test:
  secret_key_base: 3d62f08e2ee5037c17a111bdb540c431fe56d7a8db5d31901746b4a3529ab4dd63a428a6802c96f4ecef35518fcab784b2572d4a6f660ad87161104a26689ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
